//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCardCliens.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankCard", Namespace="http://schemas.datacontract.org/2004/07/BankCard")]
    [System.SerializableAttribute()]
    public partial class BankCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BiztonsagiKodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KartyaSzamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KibocsatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LejaratField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BiztonsagiKod {
            get {
                return this.BiztonsagiKodField;
            }
            set {
                if ((this.BiztonsagiKodField.Equals(value) != true)) {
                    this.BiztonsagiKodField = value;
                    this.RaisePropertyChanged("BiztonsagiKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KartyaSzam {
            get {
                return this.KartyaSzamField;
            }
            set {
                if ((this.KartyaSzamField.Equals(value) != true)) {
                    this.KartyaSzamField = value;
                    this.RaisePropertyChanged("KartyaSzam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kibocsato {
            get {
                return this.KibocsatoField;
            }
            set {
                if ((object.ReferenceEquals(this.KibocsatoField, value) != true)) {
                    this.KibocsatoField = value;
                    this.RaisePropertyChanged("Kibocsato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lejarat {
            get {
                return this.LejaratField;
            }
            set {
                if ((object.ReferenceEquals(this.LejaratField, value) != true)) {
                    this.LejaratField = value;
                    this.RaisePropertyChanged("Lejarat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBankCard", ReplyAction="http://tempuri.org/IService1/GetBankCardResponse")]
        BankCardCliens.ServiceReference1.BankCard GetBankCard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBankCard", ReplyAction="http://tempuri.org/IService1/GetBankCardResponse")]
        System.Threading.Tasks.Task<BankCardCliens.ServiceReference1.BankCard> GetBankCardAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BankCardCliens.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BankCardCliens.ServiceReference1.IService1>, BankCardCliens.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BankCardCliens.ServiceReference1.BankCard GetBankCard() {
            return base.Channel.GetBankCard();
        }
        
        public System.Threading.Tasks.Task<BankCardCliens.ServiceReference1.BankCard> GetBankCardAsync() {
            return base.Channel.GetBankCardAsync();
        }
    }
}
