//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOST.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Felhasznalo", Namespace="http://schemas.datacontract.org/2004/07/Server.Modells")]
    [System.SerializableAttribute()]
    public partial class Felhasznalo : HOST.ServiceReference1.Record {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktivEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HASHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PorfileKepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SALTField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AktivE {
            get {
                return this.AktivEField;
            }
            set {
                if ((this.AktivEField.Equals(value) != true)) {
                    this.AktivEField = value;
                    this.RaisePropertyChanged("AktivE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HASH {
            get {
                return this.HASHField;
            }
            set {
                if ((object.ReferenceEquals(this.HASHField, value) != true)) {
                    this.HASHField = value;
                    this.RaisePropertyChanged("HASH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JogID {
            get {
                return this.JogIDField;
            }
            set {
                if ((this.JogIDField.Equals(value) != true)) {
                    this.JogIDField = value;
                    this.RaisePropertyChanged("JogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PorfileKep {
            get {
                return this.PorfileKepField;
            }
            set {
                if ((object.ReferenceEquals(this.PorfileKepField, value) != true)) {
                    this.PorfileKepField = value;
                    this.RaisePropertyChanged("PorfileKep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SALT {
            get {
                return this.SALTField;
            }
            set {
                if ((object.ReferenceEquals(this.SALTField, value) != true)) {
                    this.SALTField = value;
                    this.RaisePropertyChanged("SALT");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://schemas.datacontract.org/2004/07/Server.Modells")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HOST.ServiceReference1.Jogosultsag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HOST.ServiceReference1.Felhasznalo))]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jogosultsag", Namespace="http://schemas.datacontract.org/2004/07/Server.Modells")]
    [System.SerializableAttribute()]
    public partial class Jogosultsag : HOST.ServiceReference1.Record {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeirasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SzintField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leiras {
            get {
                return this.LeirasField;
            }
            set {
                if ((object.ReferenceEquals(this.LeirasField, value) != true)) {
                    this.LeirasField = value;
                    this.RaisePropertyChanged("Leiras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Szint {
            get {
                return this.SzintField;
            }
            set {
                if ((this.SzintField.Equals(value) != true)) {
                    this.SzintField = value;
                    this.RaisePropertyChanged("Szint");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FelhasznalokNevEmail", Namespace="http://schemas.datacontract.org/2004/07/Server.DTOs")]
    [System.SerializableAttribute()]
    public partial class FelhasznalokNevEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JogosultsagNevLeiras", Namespace="http://schemas.datacontract.org/2004/07/Server.DTOs")]
    [System.SerializableAttribute()]
    public partial class JogosultsagNevLeiras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeirasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leiras {
            get {
                return this.LeirasField;
            }
            set {
                if ((object.ReferenceEquals(this.LeirasField, value) != true)) {
                    this.LeirasField = value;
                    this.RaisePropertyChanged("Leiras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznalokLista_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznalokLista_CSResponse")]
        HOST.ServiceReference1.Felhasznalo[] FelhasznalokLista_CS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznalokLista_CS", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznalokLista_CSResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.Felhasznalo[]> FelhasznalokLista_CSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloInsert", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloInsertResponse")]
        string FelhasznaloInsert(HOST.ServiceReference1.Felhasznalo record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloInsert", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloInsertResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloInsertAsync(HOST.ServiceReference1.Felhasznalo record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloUpdate", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloUpdateResponse")]
        string FelhasznaloUpdate(HOST.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloUpdate", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloUpdateResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloUpdateAsync(HOST.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloDelete", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloDeleteResponse")]
        string FelhasznaloDelete(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokService/FelhasznaloDelete", ReplyAction="http://tempuri.org/IFelhasznalokService/FelhasznaloDeleteResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloDeleteAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagokLista", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagokListaResponse")]
        HOST.ServiceReference1.Jogosultsag[] JogosultsagokLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagokLista", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagokListaResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.Jogosultsag[]> JogosultsagokListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagHozzaAd", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagHozzaAdResponse")]
        string JogosultsagHozzaAd(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagHozzaAd", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagHozzaAdResponse")]
        System.Threading.Tasks.Task<string> JogosultsagHozzaAdAsync(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagFrissit", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagFrissitResponse")]
        string JogosultsagFrissit(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagFrissit", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagFrissitResponse")]
        System.Threading.Tasks.Task<string> JogosultsagFrissitAsync(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagTorol", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagTorolResponse")]
        string JogosultsagTorol(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokService/JogosultsagTorol", ReplyAction="http://tempuri.org/IJogosultsagokService/JogosultsagTorolResponse")]
        System.Threading.Tasks.Task<string> JogosultsagTorolAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokLista_WEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokLista_WEBResponse")]
        HOST.ServiceReference1.Felhasznalo[] FelhasznalokLista_WEB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokLista_WEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokLista_WEBResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.Felhasznalo[]> FelhasznalokLista_WEBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloHozzaAd_WEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloHozzaAd_WEBResponse")]
        string FelhasznaloHozzaAd_WEB(HOST.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloHozzaAd_WEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloHozzaAd_WEBResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloHozzaAd_WEBAsync(HOST.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloUpdate_Web", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloUpdate_WebResponse")]
        string FelhasznaloUpdate_Web(HOST.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloUpdate_Web", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloUpdate_WebResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloUpdate_WebAsync(HOST.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloDelete_WEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloDelete_WEBResponse")]
        string FelhasznaloDelete_WEB(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloDelete_WEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznaloDelete_WEBResponse")]
        System.Threading.Tasks.Task<string> FelhasznaloDelete_WEBAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailCS", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailCSResponse")]
        HOST.ServiceReference1.FelhasznalokNevEmail[] FelhasznalokNevEmailCS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailCS", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailCSResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.FelhasznalokNevEmail[]> FelhasznalokNevEmailCSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailWEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailWEBResponse")]
        HOST.ServiceReference1.Felhasznalo[] FelhasznalokNevEmailWEB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailWEB", ReplyAction="http://tempuri.org/IFelhasznalokServiceWEB/FelhasznalokNevEmailWEBResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.Felhasznalo[]> FelhasznalokNevEmailWEBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/GetJogosultsagokWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/GetJogosultsagokWEBResponse")]
        HOST.ServiceReference1.Jogosultsag[] GetJogosultsagokWEB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/GetJogosultsagokWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/GetJogosultsagokWEBResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.Jogosultsag[]> GetJogosultsagokWEBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokUpdateWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokUpdateWEBResponse")]
        string JogosultsagokUpdateWEB(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokUpdateWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokUpdateWEBResponse")]
        System.Threading.Tasks.Task<string> JogosultsagokUpdateWEBAsync(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokInsertWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokInsertWEBResponse")]
        string JogosultsagokInsertWEB(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokInsertWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokInsertWEBResponse")]
        System.Threading.Tasks.Task<string> JogosultsagokInsertWEBAsync(HOST.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokDeleteWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokDeleteWEBResponse")]
        string JogosultsagokDeleteWEB(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokDeleteWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagokDeleteWEBResponse")]
        System.Threading.Tasks.Task<string> JogosultsagokDeleteWEBAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeiras", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeirasResponse")]
        HOST.ServiceReference1.JogosultsagNevLeiras[] JogosultsagNevLeiras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeiras", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeirasResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.JogosultsagNevLeiras[]> JogosultsagNevLeirasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeirasWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeirasWEBResponse")]
        HOST.ServiceReference1.Jogosultsag[] JogosultsagNevLeirasWEB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeirasWEB", ReplyAction="http://tempuri.org/IJogosultsagokServiceWEB/JogosultsagNevLeirasWEBResponse")]
        System.Threading.Tasks.Task<HOST.ServiceReference1.Jogosultsag[]> JogosultsagNevLeirasWEBAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HOST.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HOST.ServiceReference1.IService1>, HOST.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HOST.ServiceReference1.Felhasznalo[] FelhasznalokLista_CS() {
            return base.Channel.FelhasznalokLista_CS();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.Felhasznalo[]> FelhasznalokLista_CSAsync() {
            return base.Channel.FelhasznalokLista_CSAsync();
        }
        
        public string FelhasznaloInsert(HOST.ServiceReference1.Felhasznalo record) {
            return base.Channel.FelhasznaloInsert(record);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloInsertAsync(HOST.ServiceReference1.Felhasznalo record) {
            return base.Channel.FelhasznaloInsertAsync(record);
        }
        
        public string FelhasznaloUpdate(HOST.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.FelhasznaloUpdate(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloUpdateAsync(HOST.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.FelhasznaloUpdateAsync(felhasznalo);
        }
        
        public string FelhasznaloDelete(int ID) {
            return base.Channel.FelhasznaloDelete(ID);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloDeleteAsync(int ID) {
            return base.Channel.FelhasznaloDeleteAsync(ID);
        }
        
        public HOST.ServiceReference1.Jogosultsag[] JogosultsagokLista() {
            return base.Channel.JogosultsagokLista();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.Jogosultsag[]> JogosultsagokListaAsync() {
            return base.Channel.JogosultsagokListaAsync();
        }
        
        public string JogosultsagHozzaAd(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagHozzaAd(jogosultsag);
        }
        
        public System.Threading.Tasks.Task<string> JogosultsagHozzaAdAsync(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagHozzaAdAsync(jogosultsag);
        }
        
        public string JogosultsagFrissit(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagFrissit(jogosultsag);
        }
        
        public System.Threading.Tasks.Task<string> JogosultsagFrissitAsync(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagFrissitAsync(jogosultsag);
        }
        
        public string JogosultsagTorol(int ID) {
            return base.Channel.JogosultsagTorol(ID);
        }
        
        public System.Threading.Tasks.Task<string> JogosultsagTorolAsync(int ID) {
            return base.Channel.JogosultsagTorolAsync(ID);
        }
        
        public HOST.ServiceReference1.Felhasznalo[] FelhasznalokLista_WEB() {
            return base.Channel.FelhasznalokLista_WEB();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.Felhasznalo[]> FelhasznalokLista_WEBAsync() {
            return base.Channel.FelhasznalokLista_WEBAsync();
        }
        
        public string FelhasznaloHozzaAd_WEB(HOST.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.FelhasznaloHozzaAd_WEB(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloHozzaAd_WEBAsync(HOST.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.FelhasznaloHozzaAd_WEBAsync(felhasznalo);
        }
        
        public string FelhasznaloUpdate_Web(HOST.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.FelhasznaloUpdate_Web(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloUpdate_WebAsync(HOST.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.FelhasznaloUpdate_WebAsync(felhasznalo);
        }
        
        public string FelhasznaloDelete_WEB(int ID) {
            return base.Channel.FelhasznaloDelete_WEB(ID);
        }
        
        public System.Threading.Tasks.Task<string> FelhasznaloDelete_WEBAsync(int ID) {
            return base.Channel.FelhasznaloDelete_WEBAsync(ID);
        }
        
        public HOST.ServiceReference1.FelhasznalokNevEmail[] FelhasznalokNevEmailCS() {
            return base.Channel.FelhasznalokNevEmailCS();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.FelhasznalokNevEmail[]> FelhasznalokNevEmailCSAsync() {
            return base.Channel.FelhasznalokNevEmailCSAsync();
        }
        
        public HOST.ServiceReference1.Felhasznalo[] FelhasznalokNevEmailWEB() {
            return base.Channel.FelhasznalokNevEmailWEB();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.Felhasznalo[]> FelhasznalokNevEmailWEBAsync() {
            return base.Channel.FelhasznalokNevEmailWEBAsync();
        }
        
        public HOST.ServiceReference1.Jogosultsag[] GetJogosultsagokWEB() {
            return base.Channel.GetJogosultsagokWEB();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.Jogosultsag[]> GetJogosultsagokWEBAsync() {
            return base.Channel.GetJogosultsagokWEBAsync();
        }
        
        public string JogosultsagokUpdateWEB(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagokUpdateWEB(jogosultsag);
        }
        
        public System.Threading.Tasks.Task<string> JogosultsagokUpdateWEBAsync(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagokUpdateWEBAsync(jogosultsag);
        }
        
        public string JogosultsagokInsertWEB(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagokInsertWEB(jogosultsag);
        }
        
        public System.Threading.Tasks.Task<string> JogosultsagokInsertWEBAsync(HOST.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.JogosultsagokInsertWEBAsync(jogosultsag);
        }
        
        public string JogosultsagokDeleteWEB(int id) {
            return base.Channel.JogosultsagokDeleteWEB(id);
        }
        
        public System.Threading.Tasks.Task<string> JogosultsagokDeleteWEBAsync(int id) {
            return base.Channel.JogosultsagokDeleteWEBAsync(id);
        }
        
        public HOST.ServiceReference1.JogosultsagNevLeiras[] JogosultsagNevLeiras() {
            return base.Channel.JogosultsagNevLeiras();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.JogosultsagNevLeiras[]> JogosultsagNevLeirasAsync() {
            return base.Channel.JogosultsagNevLeirasAsync();
        }
        
        public HOST.ServiceReference1.Jogosultsag[] JogosultsagNevLeirasWEB() {
            return base.Channel.JogosultsagNevLeirasWEB();
        }
        
        public System.Threading.Tasks.Task<HOST.ServiceReference1.Jogosultsag[]> JogosultsagNevLeirasWEBAsync() {
            return base.Channel.JogosultsagNevLeirasWEBAsync();
        }
    }
}
